# Invoke using 'cargo +nightly fmt'.
edition = "2021"
unstable_features = true
imports_granularity = "Crate"
newline_style = "Windows"
reorder_modules = true
reorder_imports = true
format_strings = true
match_block_trailing_comma = true
merge_derives = true