#![allow(unused)]
use kernel_macros::CTL_CODE;
use km_api_sys::wmd::{FILE_ANY_ACCESS, METHOD_BUFFERED, METHOD_NEITHER};
use winapi::shared::ntdef::ULONG;

pub(super) const IOCTL_DELPROTECT_ADD_EXE: ULONG =
    CTL_CODE!(0x8000, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS);
pub(super) const IOCTL_DELPROTECT_REMOVE_EXE: ULONG =
    CTL_CODE!(0x8000, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS);
pub(super) const IOCTL_DELPROTECT_CLEAR: ULONG =
    CTL_CODE!(0x8000, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS);
