[package]
name = "km-api-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
kernel-string = { path = "../kernel-string"}

[dependencies.winapi]
git = "https://github.com/Trantect/winapi-rs.git"
branch = "feature/km"
features = [
    "wdm",
    "ntstatus",
]